/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import boundary.Panels.Panel_Intro;
import boundary.Panels.Panel_MAIN;
import control.Controller;
import interfaces.GameAbilities;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Andreas
 */
public class GUI_MAIN extends javax.swing.JFrame {

    GameAbilities control;
    JPanel panel_Main;
    JPanel panel_Intro;
    int panelNumber = 0;
    Timer timer;

    /**
     * Creates new form GUI_MAIN
     */
    public GUI_MAIN() {
        initComponents();
        control = Controller.getInstance();
        panel_Intro = new Panel_Intro();
        panel_Main = new Panel_MAIN();
        GUIController();
    }

    public void GUIController() {
        this.setLayout(new BorderLayout());
        setUpPanels();
        panelController();

    }

    public void setUpPanels() {
        this.add(panel_Intro, BorderLayout.CENTER);
        this.setVisible(true);
        
        this.add(panel_Main, BorderLayout.CENTER);
        panel_Main.setVisible(false);
       
    }

    public void panelController() {
        

        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                //timeUp = false;

                switch (panelNumber) {
                    case 0:
                        panel_Intro.setVisible(true);
                        jButtonMainFrameNextPanel.setText("Start game!");
                        break;
                    case 1:
                        panel_Intro.setVisible(false);
                        panel_Main.setVisible(true);
                        jButtonMainFrameNextPanel.setVisible(false);
                        break;
                }
            }
        };

        timer = new Timer(0, action);
        timer.setInitialDelay(0);
        timer.start();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMainFrameNextPanel = new javax.swing.JButton();
        jMainText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        jButtonMainFrameNextPanel.setText("NEXT BUTTON");
        jButtonMainFrameNextPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainFrameNextPanelActionPerformed(evt);
            }
        });

        jMainText.setBackground(new java.awt.Color(255, 255, 255));
        jMainText.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jMainText.setForeground(new java.awt.Color(102, 102, 102));
        jMainText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMainText.setText("MafiaVille BETA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainText, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMainFrameNextPanel)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jMainText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jButtonMainFrameNextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMainFrameNextPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainFrameNextPanelActionPerformed
        panelNumber++;
    }//GEN-LAST:event_jButtonMainFrameNextPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMainFrameNextPanel;
    private javax.swing.JLabel jMainText;
    // End of variables declaration//GEN-END:variables
}
